name: Issue
description: Miscellaneous issues are closed immediately. If you have no intention of returning useful information to the community, you have no right to post an issue here. Please withdraw.
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to convey the history of your problem. Sloppy issues will be closed immediately.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: true
      options:
        - Bug
        - Performance
        - Feature Request
        - Documentation Feature Request
        - Documentation Bug
        - Others
    validations:
      required: true
  - type: dropdown
    id: Operating-System
    attributes:
      label: OS
      description: What OS are you seeing the issue in? If you don't see your OS listed, please provide more details in the "Description" section above.
      multiple: true
      options:
        - Windows
        - Ubuntu
        - Mac OS
        - Other
    validations:
      required: true
  - type: dropdown
    id: Operating-System-Architecture
    attributes:
      label: OS architecture
      description: If you don't see your device listed, please provide more details in the "Description" section above.
      multiple: true
      options:
        - x86_64
        - aarch64
        - armv7
        - armv6
        - Other
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Programming Language
      description: What programming language are you using? If "Other", please provide more details in the "Description" section above.
      multiple: true
      options:
        - C++
        - Python
        - Rust
        - Go
        - Other
    validations:
      required: true
  - type: dropdown
    id: Framework
    attributes:
      label: Framework
      description: What framework are you using? If "Other", please provide more details in the "Description" section above.
      multiple: true
      options:
        - OpenVINO
        - PyTorch
        - ONNX
        - TensorFlow
        - TensorFlowLite
        - TensorFlow.js
        - TensorRT
        - TF-TRT
        - CoreML
        - Myriad Inference Engine
        - Other
    validations:
      required: true
  - type: textarea
    id: Download-URL-for-ONNX-OpenVINO-IR
    attributes:
      label: Download URL for ONNX / OpenVINO IR
      description: Please include the URL where you quoted the ONNX file or OpenVINO IR(.xml/.bin).
    validations:
      required: true
  - type: textarea
    id: Convert-script
    attributes:
      label: Convert Script
      description: Please include the convert script.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Please describe the current and expected behaviour, and attach all files/info needed to reproduce the issue if applicable.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
    validations:
      required: true
  - type: textarea
    id: url-or-source-code-for-simple-inference-testing-code
    attributes:
      label: Source code for simple inference testing code
      description: Please copy and paste source code for simple inference testing code.
